homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 150
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels

# Zones
zone:
  name: School
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:school

zone 2:
  name: SmalsCH
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:worker

zone 3:
  name: SmalsSC
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:worker

zone 4:
  name: SncbMidi
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 100
  icon: mdi:train

zone 5:
  name: SncbGbx
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 200
  icon: mdi:train

zone 6:
  name: Cortil
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 50
  icon: mdi:human-child

zone 7:
  name: GdManil
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 50
  icon: mdi:human-child

zone 8:
  name: Bcsf
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 50
  icon: mdi:soccer

# OwnTracks
#device_tracker:
#  - platform: owntracks
#    max_gps_accuracy: 100

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# MQTT Broker
mqtt:
  broker: 192.168.1.10
  port: 1883
  #username:
  #password:
  protocol: 3.1 

# Sensors
sensor:
  # Weather Prediction
  - platform: yr
  # MQTT
  - platform: mqtt
    state_topic: "home/livingroom/temperature"
    value_template: "{{ value_json.temperature }}"
    unit_of_measurement: "C"
    name: "Temperature Living"
  - platform: mqtt
    state_topic: "home/livingroom/humidity"
    value_template: "{{ value_json.humidity }}"
    unit_of_measurement: "%"
    name: "Humidity Living"
  - platform: mqtt
    state_topic: "home/outside/temperature"
    unit_of_measurement: "C"
    name: "Temperature Outside"
  - platform: mqtt
    state_topic: "home/outside/humidity"
    unit_of_measurement: "%"
    name: "Humidity Outside"
  # Synology DSM
  - platform: synologydsm
    host: 192.168.1.55
    port: 5000
    username: !secret user
    password: !secret passwd
    monitored_conditions:
      - cpu_total_load
      - memory_real_usage
      - network_up
      - network_down
      - volume_percentage_used

# InfluxDB
influxdb:
  host: 192.168.1.10
  port: 8086
  #username:
  #password:
  whitelist:
  - sensor.temperature_living
  - sensor.humidity_living
  tags:
    source: hass  

# Text to speech
tts:
  platform: google

# Groups
group: !include groups.yaml

zwave:
  device_config: !include zwave_device_config.yaml
